dist: bionic
language: minimal
env:
  - LINK=https://github.com/KhronosGroup/glTF-Validator/releases/download/2.0.0-dev.3.0%2B1/gltf_validator-2.0.0-dev.3.0+1-linux64.tar.xz
install: curl -sL $LINK | tar xJ
script: ./gltf_validator -r -a ./2.0/
